version: '3.4'

volumes:
  mysql-data: {}

services:
  server:
    image: node:12.13.1-alpine
    user: node
    working_dir: /usr/src/bridge-server
    command: npm run start:dev
    environment:
      - PORT=4000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_DB=milli_db
    ports:
      # GraphQL
      - "4000:4000"
    links:
      - mysql
    volumes:
      - .:/usr/src/bridge-server

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=milli_db
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:rw

  # e.g. docker-compose run mysql-client -e 'show tables'
  mysql-client:
    depends_on:
      - mysql
    image: mysql:5.7
    entrypoint: mysql milli_db -h mysql -uroot -psecret
